### ISSUE TITLE
Github Action Job is not aborted and set to failed when this step fails

### ISSUE THREAD

**Issue by Bascy** [mattnotmitt/doxygen-action#16]
When execution fails, i.e. because doxygen file cannot be found, the step is ended and the next step is still executed.
This will also list the Job as succeeded while it obviously has failed

**Comment by mattnotmitt** [comment]
Hi @Bascy do you have an example of this? I can't seem to replicate it.

**Comment by Bascy** [comment]
[logs_68.zip](https://github.com/mattnotmitt/doxygen-action/files/6423858/logs_68.zip)
If you look at the  doxygen log around line 61, it says 
`error: configuration file ./SenseFramework/Doxyfile-all-libs not found!`

Also showing the help text, but then still continues with the next step `upload` and ending succesfully

![image](https://user-images.githubusercontent.com/633644/117068373-7f8bcf00-ad2b-11eb-83de-9e9b3fa39218.png)

**Comment by mattnotmitt** [comment]
Yep, I see the issue. That's just me failing to actually exit my entrypoint script correctly. I'll push a new version of the action in a moment. 

I assume you know how to fix the "file not found" error though?

**Comment by Bascy** [comment]
Thanks, yes that problem is fixed now :)

**Comment by mattnotmitt** [comment]
Thanks for pointing out the issue! I'm just about to make the runtime of this action _much_ shorter as part of #18, so make sure that your actions config specifies the major v1 version like this:
```
uses: mattnotmitt/doxygen-action@v1
```
rather than a full version so you don't have to update it again.

**Comment by Bascy** [comment]
Checked!
