### ISSUE TITLE
Missing files in alpine:edge

### ISSUE THREAD

**Issue by jowr** [mattnotmitt/doxygen-action#17]
It seems like one of the latest changes in the alpine Linux distribution broke the TeX-support. This is the same issue as what #15 tries to fix, but maybe we can find the root cause rather than changing to arch Linux.

My best guess is that these refactorings in April are related: 
 - https://git.alpinelinux.org/aports/
 - https://github.com/alpinelinux/docker-alpine/commits/master

**Comment by mattnotmitt** [comment]
The main reason I was using edge in the first place was for an updated version of doxygen that wasn't in any stable versions of Alpine. I'll lock down the version to the latest stable that works later this evening.

**Comment by mattnotmitt** [comment]
I've updated the action to use alpine `3.13.3` as it was the last version that I could get it to work. This is included in release v1.3.1 and v1 tag has been updated to track this. As part of this, I've also added a v1.3 tag which will track all v1.3.x versions if someone wanted to follow that minor track.

**Comment by jowr** [comment]
Great - thank you!
