### ISSUE TITLE
Support for Doxygen's WARN_AS_ERROR

### ISSUE THREAD

**Issue by saxbophone** [mattnotmitt/doxygen-action#19]
I use Doxyfile config including the following fragment to make Doxygen always fail if there are errors in my docs:

```
# If the WARN_AS_ERROR tag is set to YES then doxygen will immediately stop when
# a warning is encountered.
# The default value is: NO.

WARN_AS_ERROR          = YES
```

On the command-line locally, this causes Doxygen to quit early, halting the doc generation process and returning non-success process exit code. I've previously used this technique for docs CI on Travis, but I noticed the docs generation failing doesn't fail the builds on Github Actions when using this action.

Is it feasible to add support for this workflow by exposing the doxygen command's exit code in the Github Action?

I know #7 is already open and is similar to this, but from what I have read on that other thread, what I'm asking about here seems to be something a bit different.

Thanks

**Comment by mattnotmitt** [comment]
Just had a bit of a test with one of my repos, and after enabling WARN_AS_ERROR and removing a piece of documentation I was able to get it to [fail](https://github.com/mattnotmitt/DelaunayTriangulation/runs/2519568155#step:4:222). Doxygen is awfully strange with how it deals with warnings - could you check that what you're calling a "warning" isn't actually a printf statement with "warning" printed at the start of it?

EDIT: Oh wait, I think I see what you mean. Let me try adding some flags to the entrypoint script so it fails properly.
