### ISSUE TITLE
If enable-latex is set to false, entrypoint script will fail.

### ISSUE THREAD

**Issue by 2bndy5** [mattnotmitt/doxygen-action#21]
Hi again. I'm raising this issue now to kinda timestamp when I noticed the build failures. 

I'm using this action on multiple repos and specifying `@v1`. but as of today it started failing to execute; even the workflows' run logs are not showing any output (just the very long cmd that was executed). Additionally (to be sure this isn't on me), I went back to an older successful workflow run and manually re-ran it; what was once successful is now failing. I'm hoping you have more insight. And to be absolutely sure, I checked doxygen's output locally on my PC: doxygen builds the docs fine locally without any warnings or errors.

**Comment by mattnotmitt** [comment]
Could you try changing the tag you're running the action from to `mattnotmitt/doxygen-action@debug`? This will print the commands running in the entrypoint script and should hopefully show what's failing.

**Comment by 2bndy5** [comment]
interesting. output is now as follows (still fails in less than 10 seconds):
```
  with:
    working-directory: .
    doxyfile-path: ./Doxyfile
    enable-latex: false
/usr/bin/docker run --name a33c1c63cf06cd7404247abbef4b40f8f6505_d634a4 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_WORKING-DIRECTORY -e INPUT_DOXYFILE-PATH -e INPUT_ENABLE-LATEX -e INPUT_ADDITIONAL-PACKAGES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/RF24Log/RF24Log":"/github/workspace" 8a33c1:c63cf06cd7404247abbef4b40f8f6505  "./Doxyfile" "." "false" ""
+ '[' '!' -d . ]
+ cd .
+ '[' '!' -f ./Doxyfile ]
+ '[' '!' -z false ]
+ BUILD_LATEX=false
+ grep -q 'GENERATE_LATEX\s*=\s*YES' ./Doxyfile
```

**Comment by mattnotmitt** [comment]
Ahh, I see what's happening - just remove the `enable-latex: false` line. You only need to specify enable-latex if you want it to be true. I'll make an adjustment to the action though so that doesn't cause an error now.

**Comment by 2bndy5** [comment]
so, I'm not actually specifying that option in the yml (never have):
```yml
    - name: build doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'
    - name: upload to github pages
```

**Comment by 2bndy5** [comment]
I looked up the log for last successful run, and that `enable-latex` option shows up in the logs but it was never specified in the yml. I went further back to a successful run that happened before your latest release, and that option still shows up (only in the run's log).

**Comment by mattnotmitt** [comment]
Ah, it might be a default flag being passed. Either way, the version I've just pushed should work. I'm really sorry that this happened. You can continue using `v1` or if you want to test this and keep it at a working static version, then `v1.3.3` will do.

**Comment by 2bndy5** [comment]
yep that did it. thanks again!
