### ISSUE TITLE
Configuring Plant uml via additional_packages 

### ISSUE THREAD

**Issue by spalaniappan-pg** [mattnotmitt/doxygen-action#23]
Hi, I would like to understand if its possible to add PlantUML into the actions via additional packages field, i tried to search for PlantUML plugin in the package but couldnt able to find it.
TIA
Suresh

**Comment by mattnotmitt** [comment]
Sadly it's not in alpine's repository so it's outside of the scope of this particular action. Feel free to fork it to add your own support though :)
