### ISSUE TITLE
Broken build on 1.9.3-r0

### ISSUE THREAD

**Issue by rasky** [mattnotmitt/doxygen-action#27]
Looks like alpine released a -r1 version of 1.9.3 so now the builds that use the action @1.9.3 are broken, as they pin the package name with -r0.

**Comment by rasky** [comment]
Example of broken build: https://github.com/DragonMinded/libdragon/runs/5954398794?check_suite_focus=true

**Comment by mattnotmitt** [comment]
Sorry about this. I've updated `doxygen-action@1.9.3` and I'm going to add a warning to the README that the 1.9.3 version may break without warning as it's on the edge branch of alpine.
