### ISSUE TITLE
Question: Does this action support LaTeX styled equations in the doxygen documentation?

### ISSUE THREAD

**Issue by tomeichlersmith** [mattnotmitt/doxygen-action#3]
I am working on a larger coding project and we are looking for a method that can automatically update our doxygen-generated documentation. Our project is physics-related, so there are several places where having equations is helpful for documenting the code.

I'm not familiar with GitHub actions, so I'm not sure if this docker image you are using has LaTeX installed in it.

**Comment by mattnotmitt** [comment]
It doesn't have the functionality to build latex PDFs, but it does support rendering LaTeX in the web output with MathJax. You can see an example of the output [here](https://mattnotmitt.github.io/DelaunayTriangulation/classTriangle.html#a45f2f690e862dc66d21fabcf890bcfe5) and the source for this function's documentation is [here](https://github.com/mattnotmitt/DelaunayTriangulation/blob/master/src/Triangle.cpp#L138). You might have to fiddle with your doxyfile to get it all working, so I'd recommend rendering it locally before starting to build it with this action.

**Comment by tomeichlersmith** [comment]
That answers my question. Thank you!

**Comment by mattnotmitt** [comment]
Happy to help!
