### ISSUE TITLE
1.9.2 segmentation fault

### ISSUE THREAD

**Issue by oiltanker** [mattnotmitt/doxygen-action#30]
https://github.com/oiltanker/LuaCsForBarotrauma/actions/runs/2347576746

**Comment by mattnotmitt** [comment]
Looks like it's happening when the action is running Doxygen itself. Does it work on a local instance of `1.9.2`? You could also try the `edge` or `1.9.1` versions of the action to see if it's a version dependent issue. If it's broken on `edge` then you might want to report a bug to the Doxygen project itself.

**Comment by oiltanker** [comment]
No idea how to do a local instance, but rolling back to 1.9.1 helped
