### ISSUE TITLE
doxygen released 1.9.5

### ISSUE THREAD

**Issue by steve02081504** [mattnotmitt/doxygen-action#32]

**Comment by mattnotmitt** [comment]
You can use `mattnotmitt/doxygen-action@edge` for the time being, I'll create a `1.9.5` tag once there's a new stable release of alpine.

**Comment by steve02081504** [comment]
> https://github.com/mattnotmitt/doxygen-action/issues/32#issuecomment-1295800787

Thanks!
I think I should close this issue after the new tag is posted to avoid any other daredevils like me

**Comment by mattnotmitt** [comment]
Version [`v1.9.5`](https://github.com/mattnotmitt/doxygen-action/releases/tag/1.9.5) has been released :)
