### ISSUE TITLE
Latex command sometimes needed but missing

### ISSUE THREAD

**Issue by TysonRayJones** [mattnotmitt/doxygen-action#36]
Hi there,

Thanks for a wonderful github action! Alas I have encountered a problem.

I _do not_ wish to generate a `latex` folder, and ergo my doxygen config file contains `GENERATE_LATEX = NO`. This means I do not need to run the final [`make`](https://github.com/mattnotmitt/doxygen-action/blob/452281fb0f5f8a3e8d3f7fa5359cb58f249dfa28/entrypoint.sh#L43) command. In fact, I wish to _avoid_ running that command altogether, since my Github Action otherwise encounters an error (`! LaTeX Error: File hierarchy.tex not found`) unrelated to this question, which I wish to avoid debugging. 

My documentation strings however _do_ include LaTeX formulae, with syntax
```
\f[
    x^2
\f]
```
This means my `html` documentation needs images of the LaTeX formulae, which Doxygen generates with LaTeX. Doxygen performs this even when `GENERATE_LATEX = NO` (the flag is very unfortunately named).

Here is my problem. Because my doxygen config file contains `GENERATE_LATEX = NO` (to avoid the above unrelated bug), the entrypoint script sets `BUILD_LATEX=0`, avoiding the `apk` installation of `texlive-full`. So while Doxygen is running, the `latex` command is undefined. Doxygen will hence complain that
```
sh: latex: not found
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
```
and be unable to generate the images needed by my `html` documentation.

The core of the issue is that you cannot consult the Doxygen config file's `GENERATE_LATEX` flag to determine whether or not to build latex. This is because the latex command is sometimes needed by html generation, when latex (document) generation is off.

I think a natural fix is to trust the user's `enable-latex` action argument to inform whether or not to build the latex command.
Then, only consult the Doxygen config file's `GENERATE_LATEX` to decide whether or not to call the final `make`.
I can happily submit this in a pull request

**Comment by mattnotmitt** [comment]
Hi Tyson, thanks for pointing this out! I didn't realise this behaviour was there (I always used Mathjax). I'd definitely accept a PR, thanks for the offer 😄 

The simplest solution, as you've said, would be to just trust the user's `enable-latex` setting, however, I'm not sure that with ~3k repos actively using this action that changing this behaviour would be too smart... I wonder if we could add a third option to that setting, e.g. `force` which if chosen will override the default behaviour. We thankfully don't have to worry about types (eek, thanks bash), so I think this would be worth a try.

**Comment by TysonRayJones** [comment]
Ahh I see, yeah an optional flag like `build-latex-cmd` could make sense.
I hadn't realised I could just use Mathjax - indeed it avoids the problem and looks 1000x better! :) 
I now vote to change nothing, to prompt other latex-wielding luddites into the light of Mathjax.  🙌
