### ISSUE TITLE
use github env vars in doxygen builds

### ISSUE THREAD

**Issue by 2bndy5** [mattnotmitt/doxygen-action#5]
any chance we could get the github env tag about projects' version number into the Doxygen config file's `PROJECT_NUMBER` tag?

I know doxygen allows for additional doxygen config files via the config's `@INCLUDE` & `@INCLUDE_PATH` tags. Maybe you could generate config file for github env vars (version, commit, author, and other stuff) before running doxygen. This would also require altering the default config file's `@INCLUDE` and/or `@INCLUDE_PATH` tags to accommodate the generated config file (with github env vars).

p.s. I see you're already using `doxygen <config_file>` in entrypoint.sh; I doubt that doxygen would support a list of config files as the CLI arg

**Comment by mattnotmitt** [comment]
Hi @2bndy5, this issue isn't really related to this action, but I've just tried it out in my test repo. If you set up your [Doxyfile](https://github.com/mattnotmitt/DelaunayTriangulation/blob/master/Doxyfile#L41) as you described and then edit your [workflow file](https://github.com/mattnotmitt/DelaunayTriangulation/blob/master/.github/workflows/build-test-docs.yml#L25) to set up the variable to be passed to my action. I don't have any tags set up on that repo to test with, but building from master, `${{ github.ref }}` gives [this](https://mattnotmitt.github.io/DelaunayTriangulation/) output to the `PROJECT_NUMBER` option and I assume this would just give you the tag name if you built on that event. Hope this helps!
