### ISSUE TITLE
not generating latex documentation

### ISSUE THREAD

**Issue by iulusoy** [mattnotmitt/doxygen-action#9]
Hi, when I put 
`enable-latex: true`
in my action file, I receive the warning
`Warning: Unexpected input(s) 'enable-latex', valid inputs are ['entryPoint', 'args', 'doxyfile-path', 'working-directory']`
and no latex output is generated (only html). I guess I have to push the latex document to my repository too, but just looking at the action output there is no latex command executed. GENERATE_LATEX is set to YES in my Doxyfile.

This is my main.yml:
name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Working directory
        working-directory: "." # default is .
        # Path to Doxyfile
        doxyfile-path: "./doc/Doxyfile" # default is ./Doxyfile
        enable-latex: true

**Comment by mattnotmitt** [comment]
If you want any non-breaking changes to the action change your
```uses: mattnotmitt/doxygen-action@v1.1.0```
to
```uses: mattnotmitt/doxygen-action@v1```
or if you want a static version, go with 
```uses: mattnotmitt/doxygen-action@v1.2.1```
